import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

DEFAULT_SPEC_PATH = Path(__file__).parents[4] / "xcp_config_defaults.json"


def load_spec(spec_path: Path = DEFAULT_SPEC_PATH) -> List[Dict[str, Any]]:
    with open(spec_path, "r", encoding="utf-8") as f:
        return json.load(f)


def _to_c_value(entry: Dict[str, Any], value: Any) -> Optional[str]:
    kind = entry.get("type")
    if kind == "define":
        return None
    if kind == "bool":
        if isinstance(value, str):
            return "XCP_ON" if value.strip().upper() in {"XCP_ON", "ON", "TRUE"} else "XCP_OFF"
        return "XCP_ON" if bool(value) else "XCP_OFF"
    if kind == "string" and isinstance(value, str) and not value.startswith('"'):
        return f"\"{value}\""
    return str(value)


def render_xcp_config(
    destination: Path,
    spec: Optional[Iterable[Dict[str, Any]]] = None,
    overrides: Optional[Dict[str, Any]] = None,
) -> None:
    overrides = overrides or {}
    spec = list(spec) if spec is not None else load_spec()

    lines = [
        "/* Auto-generated by pyxcp-appgen. Do not edit by hand. */",
        "#if !defined(__XCP_CONFIG_H)",
        "    #define __XCP_CONFIG_H",
        "",
    ]

    for entry in spec:
        name = entry["name"]
        value = overrides.get(name, entry.get("default"))
        c_value = _to_c_value(entry, value)
        if c_value is None:
            lines.append(f"#define {name}")
        else:
            lines.append(f"#define {name} ({c_value})")
    lines.append("")
    lines.append("#endif /* __XCP_CONFIG_H */")
    lines.append("")

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")


__all__ = ["DEFAULT_SPEC_PATH", "load_spec", "render_xcp_config"]
